### ISSUE TITLE
Howto edit home page

### ISSUE THREAD

**Issue by ArchGalileu** [sebousan/hugo-template#16]
Great template ;)

Can't edit homepage from CMS, any advice?

Best regards
ArchGalileu

**Comment by ArchGalileu** [comment]
Ups i know now

I'm so sorry for the question

Congratulations for this incredible template with all-in-one

Best regards
ArchGalileu

**Comment by sebousan** [comment]
In `indexes > Home` Hope is OK for you ?
Without blocks in home, you have automatically latest content.

@ArchGalileu thanks a lot !
